const productData = [
            // Moon Cakes (Signature)
            { id: 1, name: "Signature Lotus Moon Cake", category: "Moon Cake", price: 9.90, desc: "Our award-winning signature moon cake filled with premium pure lotus seed paste and a double salted egg yolk. Handcrafted to perfection.", ingredients: "Lotus seed paste, Salted egg yolk, Wheat flour, Peanut oil, Sugar.", nutrition: "Cal: 350 | Carbs: 45g | Fat: 15g | Pro: 6g", rating: 5.0, reviews: 248, stock: 50, img: "assets/images/Signature%20Lotus%20Moon%20Cake.png", badges: ["Signature", "Best Seller"] },
            { id: 2, name: "Red Bean Matcha Moon Cake", category: "Moon Cake", price: 8.90, desc: "A modern twist. Sweet red bean paste encased in a fragrant Uji matcha infused crust.", ingredients: "Red bean paste, Matcha powder, Wheat flour, Butter.", nutrition: "Cal: 310 | Carbs: 48g | Fat: 12g", rating: 4.8, reviews: 120, stock: 35, img: "assets/images/Red%20Bean%20Matcha%20Moon%20Cake.png", badges: ["New"] },
            { id: 3, name: "Truffle Chocolate Moon Cake", category: "Moon Cake", price: 11.50, desc: "Luxurious dark chocolate shell filled with rich chocolate truffle ganache.", ingredients: "Dark Chocolate 70%, Cream, Cocoa, Butter.", nutrition: "Cal: 420 | Carbs: 35g | Fat: 28g", rating: 4.9, reviews: 85, stock: 15, img: "assets/images/Truffle%20Chocolate%20Moon%20Cake.png", badges: ["Signature"] },
            { id: 4, name: "Snow Skin Durian Moon Cake", category: "Moon Cake", price: 12.90, desc: "Chilled mochi-like snow skin wrapping premium Musang King durian puree.", ingredients: "Glutinous rice flour, Musang King Durian, Sugar.", nutrition: "Cal: 280 | Carbs: 40g | Fat: 10g", rating: 4.9, reviews: 310, stock: 10, img: "assets/images/Snow%20Skin%20Durian%20Moon%20Cake.png", badges: ["Limited"] },
            { id: 5, name: "Custard Lava Moon Cake", category: "Moon Cake", price: 10.50, desc: "Buttery crust with a molten salted egg custard center that flows beautifully when cut.", ingredients: "Flour, Butter, Salted Egg, Custard powder, Milk.", nutrition: "Cal: 380 | Carbs: 40g | Fat: 20g", rating: 4.7, reviews: 190, stock: 40, img: "assets/images/Custard%20Lava%20Moon%20Cake.png", badges: ["Best Seller"] },
            { id: 6, name: "Classic Mixed Nuts Moon Cake", category: "Moon Cake", price: 9.50, desc: "Traditional savory-sweet filling packed with almonds, walnuts, seeds, and dried fruit.", ingredients: "Almonds, Walnuts, Melon seeds, Sesame, Candied pork.", nutrition: "Cal: 450 | Carbs: 35g | Fat: 25g", rating: 4.6, reviews: 75, stock: 25, img: "assets/images/Classic%20Mixed%20Nuts%20Moon%20Cake.png", badges: [] },
            
            // Pastries
            { id: 7, name: "Classic French Croissant", category: "Pastry", price: 3.90, desc: "Flaky, buttery, and baked fresh every morning. The perfect companion for your morning coffee.", ingredients: "French butter, Flour, Yeast, Sugar, Salt, Milk.", nutrition: "Cal: 270 | Carbs: 26g | Fat: 14g", rating: 4.9, reviews: 420, stock: 100, img: "assets/images/Classic%20French%20Croissant.png", badges: ["Best Seller"] },
            { id: 8, name: "Pain au Chocolat", category: "Pastry", price: 4.50, desc: "Classic croissant dough wrapped around rich dark chocolate batons.", ingredients: "Flour, Butter, Dark Chocolate, Yeast.", nutrition: "Cal: 320 | Carbs: 35g | Fat: 18g", rating: 4.8, reviews: 315, stock: 80, img: "assets/images/Pain%20au%20Chocolat.png", badges: [] },
            { id: 9, name: "Kouign-Amann", category: "Pastry", price: 4.90, desc: "Caramelized, layered pastry from Brittany. Crunchy on the outside, soft inside.", ingredients: "Flour, Butter, Sugar, Salt.", nutrition: "Cal: 340 | Carbs: 40g | Fat: 18g", rating: 4.7, reviews: 150, stock: 45, img: "assets/images/Kouign-Amann.png", badges: ["New"] },
            { id: 10, name: "Mixed Berry Danish", category: "Pastry", price: 4.80, desc: "Flaky pastry topped with vanilla custard and fresh seasonal berries.", ingredients: "Flour, Butter, Custard, Fresh Berries.", nutrition: "Cal: 290 | Carbs: 32g | Fat: 15g", rating: 4.6, reviews: 90, stock: 30, img: "assets/images/Mixed%20Berry%20Danish.png", badges: [] },
            
            // Cakes
            { id: 11, name: "Strawberry Shortcake", category: "Cake", price: 22.00, desc: "Light Japanese-style sponge cake layered with fresh cream and strawberries.", ingredients: "Cake flour, Eggs, Cream, Strawberries, Sugar.", nutrition: "Cal: 320 (slice) | Carbs: 35g | Fat: 18g", rating: 4.9, reviews: 220, stock: 12, img: "assets/images/Strawberry%20Shortcake.png", badges: ["Signature"] },
            { id: 12, name: "Dark Woods Black Forest", category: "Cake", price: 24.00, desc: "Rich chocolate sponge infused with cherry liqueur, layered with cream and cherries.", ingredients: "Chocolate, Kirsch, Cherries, Cream, Flour.", nutrition: "Cal: 410 (slice) | Carbs: 42g | Fat: 22g", rating: 4.8, reviews: 160, stock: 8, img: "assets/images/Dark%20Woods%20Black%20Forest.png", badges: [] },
            { id: 13, name: "Classic Tiramisu", category: "Cake", price: 23.00, desc: "Espresso-soaked ladyfingers layered with light mascarpone cream and dusted with cocoa.", ingredients: "Mascarpone, Espresso, Ladyfingers, Cocoa, Eggs.", nutrition: "Cal: 380 (slice) | Carbs: 30g | Fat: 26g", rating: 4.9, reviews: 290, stock: 15, img: "assets/images/Classic%20Tiramisu.png", badges: ["Best Seller"] },
            
            // Bread
            { id: 14, name: "Artisan Sourdough Loaf", category: "Bread", price: 7.50, desc: "Naturally leavened sourdough bread with a crispy crust and a chewy, open crumb.", ingredients: "Bread flour, Whole wheat flour, Water, Salt.", nutrition: "Cal: 150 (slice) | Carbs: 30g | Fat: 1g", rating: 4.7, reviews: 180, stock: 20, img: "assets/images/Artisan%20Sourdough%20Loaf.png", badges: [] },
            { id: 15, name: "French Baguette", category: "Bread", price: 3.20, desc: "Traditional crusty French baguette baked fresh twice daily.", ingredients: "Flour, Water, Yeast, Salt.", nutrition: "Cal: 130 (slice) | Carbs: 26g | Fat: 0.5g", rating: 4.6, reviews: 110, stock: 50, img: "assets/images/French%20Baguette.png", badges: [] },
            { id: 16, name: "Buttery Brioche Loaf", category: "Bread", price: 8.90, desc: "Extremely rich, tender, and slightly sweet French bread made with high egg and butter content.", ingredients: "Flour, Butter, Eggs, Milk, Sugar, Yeast.", nutrition: "Cal: 220 (slice) | Carbs: 22g | Fat: 12g", rating: 4.8, reviews: 145, stock: 15, img: "assets/images/Buttery%20Brioche%20Loaf.png", badges: [] },
            
            // Cookies
            { id: 17, name: "Sea Salt Chocolate Chip", category: "Cookie", price: 5.90, desc: "Box of 6. Chewy center, crispy edges, loaded with dark chocolate and flaky sea salt.", ingredients: "Flour, Dark Chocolate, Brown Sugar, Butter, Sea Salt.", nutrition: "Cal: 180 (each) | Carbs: 22g | Fat: 9g", rating: 4.9, reviews: 520, stock: 60, img: "assets/images/Sea%20Salt%20Chocolate%20Chip.png", badges: ["Best Seller"] },
            { id: 18, name: "Matcha Macadamia", category: "Cookie", price: 6.50, desc: "Box of 6. Premium Uji matcha cookies studded with roasted macadamia nuts and white chocolate.", ingredients: "Flour, Matcha, Macadamia, White Choc, Butter.", nutrition: "Cal: 190 (each) | Carbs: 20g | Fat: 11g", rating: 4.7, reviews: 180, stock: 40, img: "assets/images/Matcha%20Macadamia.png", badges: ["New"] },
            { id: 19, name: "Red Velvet Crinkle", category: "Cookie", price: 5.50, desc: "Box of 6. Soft, cake-like red velvet cookies coated in powdered sugar.", ingredients: "Flour, Cocoa, Butter, Sugar, Buttermilk.", nutrition: "Cal: 170 (each) | Carbs: 24g | Fat: 8g", rating: 4.6, reviews: 150, stock: 35, img: "assets/images/Red%20Velvet%20Crinkle.png", badges: [] },
            { id: 20, name: "Assorted Cookie Box", category: "Cookie", price: 18.90, desc: "A premium gift box containing 12 assorted signature cookies.", ingredients: "Various (Contains Nuts, Dairy, Gluten).", nutrition: "Varies", rating: 4.9, reviews: 310, stock: 25, img: "assets/images/Assorted%20Cookie%20Box.png", badges: ["Signature", "Gift"] },
        ];
