const productData = [
            // Moon Cakes (Signature)
            { id: 1, name: "Signature Lotus Moon Cake", category: "Moon Cake", price: 45.00, desc: "Our award-winning signature moon cake filled with premium pure lotus seed paste and a double salted egg yolk. Handcrafted to perfection.", ingredients: "Lotus seed paste, Salted egg yolk, Wheat flour, Peanut oil, Sugar.", nutrition: "Cal: 350 | Carbs: 45g | Fat: 15g | Pro: 6g", rating: 5.0, reviews: 248, stock: 50, img: "https://images.unsplash.com/photo-1632789139436-1216a69bf480?auto=format&fit=crop&w=800&q=80", badges: ["Signature", "Best Seller"] },
            { id: 2, name: "Red Bean Matcha Moon Cake", category: "Moon Cake", price: 42.00, desc: "A modern twist. Sweet red bean paste encased in a fragrant Uji matcha infused crust.", ingredients: "Red bean paste, Matcha powder, Wheat flour, Butter.", nutrition: "Cal: 310 | Carbs: 48g | Fat: 12g", rating: 4.8, reviews: 120, stock: 35, img: "https://images.unsplash.com/photo-1600565151522-861cb704041b?auto=format&fit=crop&w=800&q=80", badges: ["New"] },
            { id: 3, name: "Truffle Chocolate Moon Cake", category: "Moon Cake", price: 55.00, desc: "Luxurious dark chocolate shell filled with rich chocolate truffle ganache.", ingredients: "Dark Chocolate 70%, Cream, Cocoa, Butter.", nutrition: "Cal: 420 | Carbs: 35g | Fat: 28g", rating: 4.9, reviews: 85, stock: 15, img: "https://images.unsplash.com/photo-1549122728-f519709caa9c?auto=format&fit=crop&w=800&q=80", badges: ["Signature"] },
            { id: 4, name: "Snow Skin Durian Moon Cake", category: "Moon Cake", price: 60.00, desc: "Chilled mochi-like snow skin wrapping premium Musang King durian puree.", ingredients: "Glutinous rice flour, Musang King Durian, Sugar.", nutrition: "Cal: 280 | Carbs: 40g | Fat: 10g", rating: 4.9, reviews: 310, stock: 10, img: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80", badges: ["Limited"] },
            { id: 5, name: "Custard Lava Moon Cake", category: "Moon Cake", price: 48.00, desc: "Buttery crust with a molten salted egg custard center that flows beautifully when cut.", ingredients: "Flour, Butter, Salted Egg, Custard powder, Milk.", nutrition: "Cal: 380 | Carbs: 40g | Fat: 20g", rating: 4.7, reviews: 190, stock: 40, img: "https://images.unsplash.com/photo-1614145121029-83a9f7b68bf4?auto=format&fit=crop&w=800&q=80", badges: ["Best Seller"] },
            { id: 6, name: "Classic Mixed Nuts Moon Cake", category: "Moon Cake", price: 50.00, desc: "Traditional savory-sweet filling packed with almonds, walnuts, seeds, and dried fruit.", ingredients: "Almonds, Walnuts, Melon seeds, Sesame, Candied pork.", nutrition: "Cal: 450 | Carbs: 35g | Fat: 25g", rating: 4.6, reviews: 75, stock: 25, img: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80", badges: [] },
            
            // Pastries
            { id: 7, name: "Classic French Croissant", category: "Pastry", price: 6.50, desc: "Flaky, buttery, and baked fresh every morning. The perfect companion for your morning coffee.", ingredients: "French butter, Flour, Yeast, Sugar, Salt, Milk.", nutrition: "Cal: 270 | Carbs: 26g | Fat: 14g", rating: 4.9, reviews: 420, stock: 100, img: "https://images.unsplash.com/photo-1555507036-ab1e4006aaeb?auto=format&fit=crop&w=800&q=80", badges: ["Best Seller"] },
            { id: 8, name: "Pain au Chocolat", category: "Pastry", price: 7.50, desc: "Classic croissant dough wrapped around rich dark chocolate batons.", ingredients: "Flour, Butter, Dark Chocolate, Yeast.", nutrition: "Cal: 320 | Carbs: 35g | Fat: 18g", rating: 4.8, reviews: 315, stock: 80, img: "https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=800&q=80", badges: [] },
            { id: 9, name: "Kouign-Amann", category: "Pastry", price: 8.00, desc: "Caramelized, layered pastry from Brittany. Crunchy on the outside, soft inside.", ingredients: "Flour, Butter, Sugar, Salt.", nutrition: "Cal: 340 | Carbs: 40g | Fat: 18g", rating: 4.7, reviews: 150, stock: 45, img: "https://images.unsplash.com/photo-1626263468007-95724538e137?auto=format&fit=crop&w=800&q=80", badges: ["New"] },
            { id: 10, name: "Mixed Berry Danish", category: "Pastry", price: 8.50, desc: "Flaky pastry topped with vanilla custard and fresh seasonal berries.", ingredients: "Flour, Butter, Custard, Fresh Berries.", nutrition: "Cal: 290 | Carbs: 32g | Fat: 15g", rating: 4.6, reviews: 90, stock: 30, img: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=800&q=80", badges: [] },
            
            // Cakes
            { id: 11, name: "Strawberry Shortcake", category: "Cake", price: 45.00, desc: "Light Japanese-style sponge cake layered with fresh cream and strawberries.", ingredients: "Cake flour, Eggs, Cream, Strawberries, Sugar.", nutrition: "Cal: 320 (slice) | Carbs: 35g | Fat: 18g", rating: 4.9, reviews: 220, stock: 12, img: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=800&q=80", badges: ["Signature"] },
            { id: 12, name: "Dark Woods Black Forest", category: "Cake", price: 50.00, desc: "Rich chocolate sponge infused with cherry liqueur, layered with cream and cherries.", ingredients: "Chocolate, Kirsch, Cherries, Cream, Flour.", nutrition: "Cal: 410 (slice) | Carbs: 42g | Fat: 22g", rating: 4.8, reviews: 160, stock: 8, img: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80", badges: [] },
            { id: 13, name: "Classic Tiramisu", category: "Cake", price: 48.00, desc: "Espresso-soaked ladyfingers layered with light mascarpone cream and dusted with cocoa.", ingredients: "Mascarpone, Espresso, Ladyfingers, Cocoa, Eggs.", nutrition: "Cal: 380 (slice) | Carbs: 30g | Fat: 26g", rating: 4.9, reviews: 290, stock: 15, img: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=800&q=80", badges: ["Best Seller"] },
            
            // Bread
            { id: 14, name: "Artisan Sourdough Loaf", category: "Bread", price: 12.00, desc: "Naturally leavened sourdough bread with a crispy crust and a chewy, open crumb.", ingredients: "Bread flour, Whole wheat flour, Water, Salt.", nutrition: "Cal: 150 (slice) | Carbs: 30g | Fat: 1g", rating: 4.7, reviews: 180, stock: 20, img: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80", badges: [] },
            { id: 15, name: "French Baguette", category: "Bread", price: 5.00, desc: "Traditional crusty French baguette baked fresh twice daily.", ingredients: "Flour, Water, Yeast, Salt.", nutrition: "Cal: 130 (slice) | Carbs: 26g | Fat: 0.5g", rating: 4.6, reviews: 110, stock: 50, img: "https://images.unsplash.com/photo-1597079910443-60c43fc4f729?auto=format&fit=crop&w=800&q=80", badges: [] },
            { id: 16, name: "Buttery Brioche Loaf", category: "Bread", price: 14.00, desc: "Extremely rich, tender, and slightly sweet French bread made with high egg and butter content.", ingredients: "Flour, Butter, Eggs, Milk, Sugar, Yeast.", nutrition: "Cal: 220 (slice) | Carbs: 22g | Fat: 12g", rating: 4.8, reviews: 145, stock: 15, img: "https://images.unsplash.com/photo-1600180479708-54c30c88340d?auto=format&fit=crop&w=800&q=80", badges: [] },
            
            // Cookies
            { id: 17, name: "Sea Salt Chocolate Chip", category: "Cookie", price: 18.00, desc: "Box of 6. Chewy center, crispy edges, loaded with dark chocolate and flaky sea salt.", ingredients: "Flour, Dark Chocolate, Brown Sugar, Butter, Sea Salt.", nutrition: "Cal: 180 (each) | Carbs: 22g | Fat: 9g", rating: 4.9, reviews: 520, stock: 60, img: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80", badges: ["Best Seller"] },
            { id: 18, name: "Matcha Macadamia", category: "Cookie", price: 20.00, desc: "Box of 6. Premium Uji matcha cookies studded with roasted macadamia nuts and white chocolate.", ingredients: "Flour, Matcha, Macadamia, White Choc, Butter.", nutrition: "Cal: 190 (each) | Carbs: 20g | Fat: 11g", rating: 4.7, reviews: 180, stock: 40, img: "https://images.unsplash.com/photo-1618361622329-37326cc7d471?auto=format&fit=crop&w=800&q=80", badges: ["New"] },
            { id: 19, name: "Red Velvet Crinkle", category: "Cookie", price: 18.00, desc: "Box of 6. Soft, cake-like red velvet cookies coated in powdered sugar.", ingredients: "Flour, Cocoa, Butter, Sugar, Buttermilk.", nutrition: "Cal: 170 (each) | Carbs: 24g | Fat: 8g", rating: 4.6, reviews: 150, stock: 35, img: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80", badges: [] },
            { id: 20, name: "Assorted Cookie Box", category: "Cookie", price: 35.00, desc: "A premium gift box containing 12 assorted signature cookies.", ingredients: "Various (Contains Nuts, Dairy, Gluten).", nutrition: "Varies", rating: 4.9, reviews: 310, stock: 25, img: "https://images.unsplash.com/photo-1525201548942-d8732f6617a0?auto=format&fit=crop&w=800&q=80", badges: ["Signature", "Gift"] }
        ];
